language: kotlin
jdk:
- oraclejdk13
stages:
- name: build
- name: publish
  if: branch = master AND type != pull_request
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
jobs:
  include:
  - stage: build
    before_install:
    - chmod +x gradlew
    - chmod +x gradle/wrapper/gradle-wrapper.jar
    script:
    - "./gradlew clean build test"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: publish
    script:
    - ./gradlew clean build test publish -Psigning.keyId="$GPG_KEY_ID" -Psigning.password="$GPG_PASSPHRASE"
      -Psigning.secretKeyRingFile="$TRAVIS_BUILD_DIR/deploy.gpg" -PossrhUsername="$SONATYPE_USERNAME"
      -PossrhPassword="$SONATYPE_PASSWORD"
    - ./gradlew closeAndReleaseRepository  -PossrhUsername="$SONATYPE_USERNAME"
      -PossrhPassword="$SONATYPE_PASSWORD"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
    before_install:
    - chmod +x gradlew
    - chmod +x gradle/wrapper/gradle-wrapper.jar
    - openssl aes-256-cbc -K $encrypted_c76e7fd9c81f_key -iv $encrypted_c76e7fd9c81f_iv
      -in deploy.gpg.enc -out deploy.gpg -d

env:
  matrix:
  - CI_SERVER=true
  global:
  - secure: cbS8SeSoMWhkRP8aHfKb49EI1d1kv1aJ4YCP9GForVXjhwEpvK+DixD3ficr4ua/JcLeKuV4G//j4Ra8tvr9yr7ETQbGO1AjdDpdvbLAWMA5ctlSmDu08yx+dP5PfKmKyFZIlYi4ikwhFRPtzgPP0aczINiVTUDx5YaWLapiHVST0y7XQhX+BDzOPi9jWhBoYbwzptORpr75OZd2tznhbffo6Jc/qYTDIu8A74EW/gSINvh6P2B2hMCbItI26GbvWvJYFEWiHGNY6lhmKWDjb5evR8Tx6AUhioRyuhYpyTSdK2lWwq9oFjk26UlTWIH2D1KwY1H76lCQYebU2HfeX6dF6nKOe1cW6ArKDzfWj50cr8rME/n5Wxo0DAi3ola5+A2OFIJLzlansVTtNTh/v5dFnnSh1hkjTT0WKQ5y1zgaW/mZ5HTUj8EiLIBSLA64wEizAflDdpSykQqAIUtwrvgn2AS3QnR5k3403mUq7iNAt0hzSR+xHxHUvZVv90ZAzhsch0TBJOX1ZaAfzxot9AAXfXY0036Hr/WKT94G2PGVnLbnVqbdNksHcK1ZPrYQLM1XalCZoL+z5raXdNXDNHjeQ5cFnKiVq6dn2Me7jlt+Ck6AMrXrHZcTtB8pdIVyCIscLoOIQhc/+mhI8OEO+JhY4rKKyzLE+GkyyK774Uc=
  - secure: T24Vbt69qIemBVgrDBkVsf1hZkU5b+9MOaCeY0Hg5DZBJoRqBqlQKXsfrVvTpfK5iwL++k7+uy/p+uwgjfRL7TsLAV2hn/e7ZtRSwwDX6t5VhoB3cU5xcttiWBsImEQRE49o8zSckzIxLc4h0fXwA64aa4gRGunNgmaV41kBC8tBzNZE7c2LNP2OeUBFuF/Xcya20s3aP96jfW98ERO7UQMOzSM2eXmPKuwxO0rsfrdair/96HvQsPYr/QXNQgsm+Ns5KcJqktFan+VWx/7dgdoHw/WZr6veyyLxEQQcbT1iN0b+ye0rx0kQFI/bYk61HFATzNfygFUIUdgDiQ1mrbIxqQMnNBtiiO1+Oo2xL+Q56SZWzoEHQRjUacIb7omrIXTsZQUq/v+vZvb6oSZJ/GV6X6SrCOmVlwd8JvCBnXakMlnV0H37VHiS1Xy/o5yzY+H1dF3UxUrzUgOUai5R6PWykI9nf1BXXFOnSycDxPdk6e+6MPCeudDJD7NqASGcS9L6Vf/G648CF6PZTtSxcTrXuUYj9ihS9tSgYLtxHj7Q0rFk5jFEthxVdB9Z+jvid3CU+Jr6KEd0BLp2nQdCbnqj5K6ZbW/DG2VxV7Og5Au8339bOglEvu5cDXx2RC55hkINagr72k1fwNY+nPWPedyABjpveNrxTIOaMR+KHQI=
  - secure: pDjdkvMZt3pra5ikbsb8wfKspmMk4GGvSa2Z9xFY2D0pCtZevB7M9u+QA63UhXcvxwWAQCaohE8/wPqOISAKmq1GYYG3YJbXV0MEAOJdmWajMmV/ScGW5qDAC2IScBMsoO+MG2lBwh5Ai0yO57349rejZPnvn6VIkyzWkzzkTb8Slh4xvf6IPwaOmHXxvkD41FnIWV58kmutZi3eYZqoBW7wWrstKrHs/kr/SZcum96rCMlMSm66X2798dHmSIODbzL0b9ljQlRDOxc0XbgfBB92A4nuS2BiUNMh/7n9xFbOmzpQVctt1uJQH0GvGh9B44YhXvLnB4DplR07inBm2D9ZLQ4ITjblJrMpUBFPESlXvUMJqk6t8i/zxt8htFC4QCzzYD2FkKPHy+xWHReKu0UMnpE2NhzdxdugJ9BHNM1Ci+Mz+4fdDHHCXV4S7Yyz0z+J7SEgDCFAA2ZGHhYP7qaHGaZjcfn+cpYTvg7XuDR74IyZvrYEajEgCiRCvvVZ2XNoie99/ERg6NrrIj5QoP3ZZo6KWO1TtzMD5GFC+exiUGTyFE/f5UUe2Lvx9Mc5IfxubFCbcWiFhU9XmoYE9ThI0XrUe2OxOTIOU/B9n38KyGjuatwZhfJMQ1URK1Kllv0cUSjrZLkz5tUWM1W5iWUkZN7atNeNa1aV7J77sks=
  - secure: UjQBKcwzhvVJZsbgi6b1Z0BZ7Bm9GbXiuynRLASZH3tC5iOvgBvnLAfTo8gTZE4+k881pbFDq0xZ/ZTVTSo7H3I2D/vUL+IUy92RNNAV9uW1CfUAw+PINWk2VQTg14b2WSzQjBUFOVTZO+8YnWPvxmUafVLZXDbHAIJMBypsaTsjh90gHzDX05Zp8ufGVeyywY3R4xCy20uhqhLktAhHOpKEDWyMpL/H4NOl09aEZR0QiFmcpbz+H0OIGMrheurKBetFIwa3yfPkHJjbOrmy2dTsn6+O4/vw78u49nPN77JYKna19Q7yHYhiOCgM9kCzpizMTUtMCk8cNo8gEcKjehKwznC9SdSgXm1GkyXpLQYR0QBkL2j+gqzVhXy6qNEH5oo6CzPDReOkij+XQsFFMVvihuUoiJ3i0SqU/5PfHolnroK6jbUMcMwVj/Vixlbh3c9SpMqoASCwE68af3F1H/uEi95A2/ChREo9OUKhkrX3lfouLz8DoHiXtNmJvH0BYukjJ9FSgKT0cYMWF+cKg83DmFmg2yqOFtZpV/wbZu2qXJGri5uRoxVVyUczXZxANmKjjqUJ02h3ypP+6FU32lZKJUXZQwyc//85aCZIkhKg0i2hZSBtD/fO7I6MqWSunjodSfjE/rAJBy5slIKt7ksqKnb4mk325RhGOD9fdJM=
