language: kotlin
jdk:
  - oraclejdk13
stages:
- name: build
- name: publish
  if: branch = master AND type != pull_request
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
jobs:
  include:
  - stage: build
    before_install:
    - chmod +x gradlew
    - chmod +x gradle/wrapper/gradle-wrapper.jar
    script:
    - "./gradlew clean build test"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: publish
    script:
    - ./gradlew clean build test publish -Psigning.keyId="$GPG_KEY_ID" -Psigning.password="$GPG_PASSPHRASE"
      -Psigning.secretKeyRingFile="$TRAVIS_BUILD_DIR/secret.gpg" -PossrhUsername="$SONATYPE_USERNAME"
      -PossrhPassword="$SONATYPE_PASSWORD"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
    before_install:
    - chmod +x gradlew
    - chmod +x gradle/wrapper/gradle-wrapper.jar
env:
  - CI_SERVER=true
  global:
  - secure: LiF1P2nNc171YEcEEg4yDevFChlzzGO20Cw4sZK6Z2hxDdumxz47/iIkxuCktFSymTrceTy2fp1F9JDpb49Z+CT4JLOGa6w3O7drrQyKKWWSFRQZ08+nQJ6Yua7ORYnrv9EPWEGpau0IrLipKupq4uwFOGjjB3bnVrjtPWLdNF+X0aGmH+g/FRtxHzJAj4FJ96kPURcTzsRdkCCWT0oNRUMMly/QiECuUIH4pmZAR+x2Jp683GXZDzelJ/xN3y6wiPl26Mv0QM94xg4keRoQUjz/NTlbZMqpHepxJ2gQpaclwK9kAFPqAdpMtrBCnyVjVMeZ2DOdAAmEYE+6UJvMRjKfaoKq9A9w351RpJkbPcy9pmDtTLEABRcwTbP7jLdFiAR0CXzsuYLe31Y0xIylBdRZi/nI4pVj/Xw/LlgN8YtyiyNTcStrqpyYU2MGWnAdvgE9sP9+Pqzqli4kFqF07rX2pGOUfHz5c6ycO03+UjdC6U6xc0AvmrbhEUwR1H793zuokdUnxinZYklFv5OBmrgCm/hX1u4p8BEpmkeuNZMUdfDBQlGchndH12ZHQg85j6W3+J9gVTQtx6FBbY4S9DVY7sPApVepiMdVAyKFAH4YkAIoSeAVsSuhW8lgWAUp6dMF+CQ7VS46S+JCtRadU2NN8Ck8KoXHwAGHRV3xmYE=
  - secure: jYFdTgG/gNYQypHntqGnyILtCOfyo2U7Bsj5ibIVHOmS4hafAIC92MiOd+gNR8riCLbNmnVv5OEWCn9bEV46HjCa0/iHQiSiRKyWNNUYYIe5iwwtjpZ0waNLDHVM1vUMX77NFhJCq+sOnEjQFQGJ186KW4eQ5CT5kymlXKITwgPwo/aCTXY6XJaWJaUt6WJFicuhxBko4c/2R48HZbJrLRbZz0kJiftDPd/6bBpDWlH6eEakD5qguFRnoDPy1PIMHpm59cIo623H6DhDNhoAlUYx/elqEdAxxhJGzQcmaQPl+uHa8zsE2xZKjSsiAeK8+htMFV8XmRGKlwNhOBgSbcZBVzAWjRNMt7pWp5tTqeycBIEO713ZPs9hojLIG5hUfRVxtoZo9Xyyce8E5dQo77gKnth0bG3Ca5WUQkwzw8sfXIP7wb9/mf7sifBcfGFgeiEMi29C3XU8TKANZyp7M/KvBEAzXqSSxddtiyp0G46k1MzwWc9REaSloK//4S2FItinLUcx1/qAAOW/+G5d7TQ7DJJEgaFekrkvautEGmlmUW79arhMyZau8lZ8E5Vp/S0mCqDuoUJuPwIfpYxnAIrh2qckJ+eRK+cSkogql8h23TwaU3J2NCtOr0tv5d9KznPOnMD5VEAay7syZ8j/G/vXPDnBguX73Eh8XtnhAME=
  - secure: e7rQ9oQoqycPaHwNvSHScv6lApz+ZXXT9ZHmAAcIo6WXb/Pb2KjbqJANxnE+7fep8PEodkUFjM69h8847FUX0QKfKYNYxTDoUl5h4jAaF7yi4pStBX4BMBmzogKgwf847jDVwZ1bf6OOMfQlfxdzs+Rt3lFsnGJuLQ1PWMw8cmw1RIzzoWl2vL52degzKZwkjsnFIQHU40NZctgIvSWVZVVOpbcb7821XydY8sl2WYYsgbT78pFrCO5a3PEQnkNlHKWg9R5uW9y9bGbMkonnheLx5GM1+AxScvOy43ZfZ2fKOw41xF7LzK2HNL1U1zeLZlKAPVofGV9gN3P4ZnJmA3syh5cfsWd0Z2GpiZT5upx2P8mJglrVY3tB5keQo+1HXYz0I5OPd633zqir0lEJw1X7qIyDKCerzCPBnxzZI3oHe93tYVba8gfa88AeCCFgQUi0qcx4iaycWqHTp9CI9dhIlNHVtkJxRy1RWjjJ6hkLY6i/ZA0wQsWgpVJjLqgx7N9GxDni6aqMtwQAkens6OD35yNlAxYmDhaqkkwh0FKp7FtVAXg6toCBGr443vrP11gWNEaCS4KuyeUf+SYNtKFCnIEjOuKKQsGq9NYpNwxM1CFPVStZz9Lo8GWXT/3NGGW+F9H12KuCivgCybM0SX4/E+SUC8afMMzacYVuER8=
  - secure: d3H3jaSPb1Q96NCl0eiwzcHYFlUxBZ4fEL8QnIVQ09h1wkNlKL07dXC7KsKIsRVhkRwcKW3dSTqd6lJMlyTS+cl4vz6cy8oA1bxdV8r/sYNmeShoincSICMTcqvImJjZG3WdsYRP46lO4tFA6qCkdUqUp/Exx/8SaQB87V65B/1YHRN+D4bnbAvYUasqGjweF11yM0UnfpvkZbUYIyIMk/if2tZbFGQzyN5IB2UdxUlils+R/ItWUCfdI+oRK5AZEUWb7cG30XhTFHdP1fd8fi/dcyEC4nAGm9L9wHHSJfnv6UZsB7mrhISvb9Jo86XKQ5aEol96LJo8gvkSuWuOn0UA6NdnXyApSncQ3B/zd3Zy34vGpe9PEcG0ukue1vYk5V0Yjmqu7zDNShapmZOk83lFqr7DxJbS2gGlqtb2L8eZANpa5BtVQ62/2/0RMOQocsAjFNtjiOlCzVQRhPgn4G/596N7dB786yuwQqLht349WEkcYnYg2cp48IGBFxrLYnXsOyF8CVQAtjP6k04Ln8wTEi3+dqTGUgcBpH1e6D/02JeJt6CO6Vt46YnxGASemeNvowOWjBNo2vSkvGIb/POMNH1OUL534VAYNrGRnRmm7c2f3cpQPA18mAs/rGKZ4DLMMuhITd89bnl9jV9eLXlrI8/Mo+Mv853NXcwMkxI=
before_install:
- openssl aes-256-cbc -K $encrypted_c76e7fd9c81f_key -iv $encrypted_c76e7fd9c81f_iv
  -in deploy.gpg.enc -out secring.gpg -d
